:_mod-docs-content-type: ASSEMBLY
[id="cert-manager-operator-install"]
= Installing the {cert-manager-operator}
include::_attributes/common-attributes.adoc[]
:context: cert-manager-operator-install

toc::[]

[role="_abstract"]
The {cert-manager-operator} is not installed in {product-title} by default. You can install the {cert-manager-operator} by using the web console.

[NOTE]
====
The operator sets `features.operators.openshift.io/token-auth-aws`, `features.operators.openshift.io/token-auth-azure`, `features.operators.openshift.io/token-auth-gcp` annotations in the operator CSV, and console asks to provide the relevant credentials details when these annotations are set. Currently, the operator does not make use of the values collected by the console and users should follow https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/security_and_compliance/cert-manager-operator-for-red-hat-openshift. Users can provide any dummy value when asked for the input. For example, when installing on ROSA, the `identity-provider-arn` is asked and any value can be provided to proceed.
====

[IMPORTANT]
====
The {cert-manager-operator} version 1.15 or later supports the `AllNamespaces`, `SingleNamespace`, and `OwnNamespace` installation modes. Earlier versions, such as 1.14, support only the `SingleNamespace` and `OwnNamespace` installation modes.
====

== Installing the {cert-manager-operator}
// Installing the {cert-manager-operator} using the web console
include::modules/cert-manager-install-console.adoc[leveloffset=+2]

//Installing using CLI
include::modules/cert-manager-install-cli.adoc[leveloffset=+2]

[role="_additional-resources"]
.Additional resources
* xref:../cert_manager_operator/index.adoc#cert-manager-operator-supported-versions_cert-manager-operator-about[Supported {cert-manager-operator} versions]

// Updating paths for the {cert-manager-operator}
include::modules/cert-manager-operator-update-channels.adoc[leveloffset=+1]

[role="_additional-resources"]
[id="cert-manager-operator-install_additional-resources"]
== Additional resources

* xref:../../operators/admin/olm-adding-operators-to-cluster.adoc#olm-adding-operators-to-a-cluster[Adding Operators to a cluster]
* xref:../../operators/admin/olm-upgrading-operators.adoc#olm-upgrading-operators[Updating installed Operators]
